select distinct ?HotelProperName ?HotelCityCodeIdentifierlatitude ?HotelCityCodeIdentifierlongitude ?HotelCityProperName ?HotelCityStateAbbreviatedName ?HotelStreetAddress ?HotelPostalZoneZipCode  ?AirportProperName ?AirportCodeIdentifierlongitude ?AirportCodeIdentifierlatitude ?AirportActOfFacilityUseActionPermission ?AirportCityCodeIdentifier ?AirportCityCountyProperName ?AirportCityProperName ?AirportCityGeospatialRegionCodeIdentifier ?AirportStateAbbreviatedName ?AirportAbbreviatedName ?AirportActOfOwnershipNominalMeasurementInformationContentEntity  
Where {
?Hotelvar0 a <http://www.ontologyrepository.com/CommonCoreOntologies/ZipCode>.
?Hotelvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/designates> ?Hotelvar1.
?Hotelvar1 a <http://www.ontologyrepository.com/CommonCoreOntologies/PostalZone>.
?Hotelvar1 <http://www.obofoundry.org/ro/ro.owl#location_of> ?Hotelvar2.
?Hotelvar2 a <http://www.ontologyrepository.com/CommonCoreOntologies/Hotel>.
?Hotelvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Hotelvar3.
?Hotelvar3 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Hotelvar3 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar4.
?Hotelvar4 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar4 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?HotelProperName.
?Hotelvar2 <http://www.obofoundry.org/ro/ro.owl#located_in> ?Hotelvar6.
?Hotelvar6 a <http://www.ontologyrepository.com/CommonCoreOntologies/City>.
?Hotelvar6 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Hotelvar7.
?Hotelvar7 a <http://www.ontologyrepository.com/CommonCoreOntologies/CodeIdentifier>.
?Hotelvar7 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar8.
?Hotelvar8 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar8 <http://www.ontologyrepository.com/CommonCoreOntologies/has_latitude_value> ?HotelCityCodeIdentifierlatitude.
?Hotelvar8 <http://www.ontologyrepository.com/CommonCoreOntologies/has_longitude_value> ?HotelCityCodeIdentifierlongitude.
?Hotelvar6 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Hotelvar11.
?Hotelvar11 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Hotelvar11 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar12.
?Hotelvar12 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar12 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?HotelCityProperName.
?Hotelvar6 <http://www.obofoundry.org/ro/ro.owl#located_in> ?Hotelvar14.
?Hotelvar14 a <http://www.ontologyrepository.com/CommonCoreOntologies/State>.
?Hotelvar14 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Hotelvar15.
?Hotelvar15 a <http://www.ontologyrepository.com/CommonCoreOntologies/AbbreviatedName>.
?Hotelvar15 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar16.
?Hotelvar16 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar16 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?HotelCityStateAbbreviatedName.
?Hotelvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Hotelvar18.
?Hotelvar18 a <http://www.ontologyrepository.com/CommonCoreOntologies/StreetAddress>.
?Hotelvar18 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar19.
?Hotelvar19 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar19 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?HotelStreetAddress.
?Hotelvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Hotelvar21.
?Hotelvar21 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Hotelvar21 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?HotelPostalZoneZipCode.
?Airportvar0 a <http://www.ontologyrepository.com/CommonCoreOntologies/NominalMeasurementInformationContentEntity>.
?Airportvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/is_a_nominal_measurement_of> ?Airportvar1.
?Airportvar1 a <http://www.ontologyrepository.com/CommonCoreOntologies/ActOfOwnership>.
?Airportvar1 <http://www.obofoundry.org/ro/ro.owl#has_participant> ?Airportvar2.
?Airportvar2 a <http://www.ontologyrepository.com/CommonCoreOntologies/Airport>.
?Airportvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar3.
?Airportvar3 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Airportvar3 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar4.
?Airportvar4 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar4 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportProperName.
?Airportvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar6.
?Airportvar6 a <http://www.ontologyrepository.com/CommonCoreOntologies/CodeIdentifier>.
?Airportvar6 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar7.
?Airportvar7 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar7 <http://www.ontologyrepository.com/CommonCoreOntologiecs/LewisianRelationOntology/has_longitude_value> ?AirportCodeIdentifierlongitude.
?Airportvar7 <http://www.ontologyrepository.com/CommonCoreOntologies/has_latitude_value> ?AirportCodeIdentifierlatitude.
?Airportvar2 <http://www.obofoundry.org/ro/ro.owl#participates_in> ?Airportvar10.
?Airportvar10 a <http://www.ontologyrepository.com/CommonCoreOntologies/ActOfFacilityUse>.
?Airportvar10 <http://www.ontologyrepository.com/CommonCoreOntologies/prescribed_by> ?Airportvar11.
?Airportvar11 a <http://www.ontologyrepository.com/CommonCoreOntologies/ActionPermission>.
?Airportvar11 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar12.
?Airportvar12 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar12 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportActOfFacilityUseActionPermission.
?Airportvar2 <http://www.obofoundry.org/ro/ro.owl#located_in> ?Airportvar14.
?Airportvar14 a <http://www.ontologyrepository.com/CommonCoreOntologies/State>.
?Airportvar14 <http://www.obofoundry.org/ro/ro.owl#location_of> ?Airportvar15.
?Airportvar15 a <http://www.ontologyrepository.com/CommonCoreOntologies/City>.
?Airportvar15 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar16.
?Airportvar16 a <http://www.ontologyrepository.com/CommonCoreOntologies/CodeIdentifier>.
?Airportvar16 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar17.
?Airportvar17 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar17 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportCityCodeIdentifier.
?Airportvar15 <http://www.obofoundry.org/ro/ro.owl#located_in> ?Airportvar19.
?Airportvar19 a <http://www.ontologyrepository.com/CommonCoreOntologies/County>.
?Airportvar19 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar20.
?Airportvar20 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Airportvar20 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar21.
?Airportvar21 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar21 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportCityCountyProperName.
?Airportvar15 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar23.
?Airportvar23 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Airportvar23 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar24.
?Airportvar24 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar24 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportCityProperName.
?Airportvar15 <http://www.obofoundry.org/ro/ro.owl#located_in> ?Airportvar26.
?Airportvar26 a <http://www.ontologyrepository.com/CommonCoreOntologies/GeospatialRegion>.
?Airportvar26 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar27.
?Airportvar27 a <http://www.ontologyrepository.com/CommonCoreOntologies/CodeIdentifier>.
?Airportvar27 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar28.
?Airportvar28 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar28 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportCityGeospatialRegionCodeIdentifier.
?Airportvar14 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar30.
?Airportvar30 a <http://www.ontologyrepository.com/CommonCoreOntologies/AbbreviatedName>.
?Airportvar30 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar31.
?Airportvar31 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar31 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportStateAbbreviatedName.
?Airportvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Airportvar33.
?Airportvar33 a <http://www.ontologyrepository.com/CommonCoreOntologies/AbbreviatedName>.
?Airportvar33 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar34.
?Airportvar34 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar34 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportAbbreviatedName.
?Airportvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/inheres_in> ?Airportvar36.
?Airportvar36 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Airportvar36 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?AirportActOfOwnershipNominalMeasurementInformationContentEntity.
}