select distinct ?PersonResidentialFacilityGeospatialRegionGeospatialRegionIdentifierLatitude ?PersonResidentialFacilityGeospatialRegionGeospatialRegionIdentifierLongitude ?PersonResidentialFacilityLocalAdministrativeRegionCountyStateDesignativeName ?PersonResidentialFacilityLocalAdministrativeRegionCountyDesignativeName ?PersonResidentialFacilityPostalZonePostalCode ?PersonResidentialFacilityStreetAddress ?PersonFamilyName ?PersonGivenName  
where{
?Personvar0 a <http://www.w3.org/1999/02/22-rdf-syntax-ns#Description>.
?Personvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/agent_in> ?Personvar1.
?Personvar1 a <http://www.ontologyrepository.com/CommonCoreOntologies/ActOfResiding>.
?Personvar1 <http://www.ontologyrepository.com/CommonCoreOntologies/has_object> ?Personvar2.
?Personvar2 a <http://www.ontologyrepository.com/CommonCoreOntologies/ResidentialFacility>.
?Personvar2 <http://purl.obolibrary.org/obo/RO_0001025> ?Personvar3.
?Personvar3 a <http://www.ontologyrepository.com/CommonCoreOntologies/GeospatialRegion>.
?Personvar3 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar4.
?Personvar4 a <http://www.ontologyrepository.com/CommonCoreOntologies/GeospatialRegionIdentifier>.
?Personvar4 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar5.
?Personvar5 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar5 <http://www.ontologyrepository.com/CommonCoreOntologies/has_latitude_value> ?PersonResidentialFacilityGeospatialRegionGeospatialRegionIdentifierLatitude.
?Personvar5 <http://www.ontologyrepository.com/CommonCoreOntologies/has_longitude_value> ?PersonResidentialFacilityGeospatialRegionGeospatialRegionIdentifierLongitude.
?Personvar2 <http://purl.obolibrary.org/obo/RO_0001025> ?Personvar8.
?Personvar8 a <http://www.ontologyrepository.com/CommonCoreOntologies/LocalAdministrativeRegion>.
?Personvar8 <http://purl.obolibrary.org/obo/BFO_0000050> ?Personvar9.
?Personvar9 a <http://www.ontologyrepository.com/CommonCoreOntologies/County>.
?Personvar9 <http://purl.obolibrary.org/obo/BFO_0000050> ?Personvar10.
?Personvar10 a <http://www.ontologyrepository.com/CommonCoreOntologies/State>.
?Personvar10 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar11.
?Personvar11 a <http://www.ontologyrepository.com/CommonCoreOntologies/DesignativeName>.
?Personvar11 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar12.
?Personvar12 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar12 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?PersonResidentialFacilityLocalAdministrativeRegionCountyStateDesignativeName.
?Personvar9 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar14.
?Personvar14 a <http://www.ontologyrepository.com/CommonCoreOntologies/DesignativeName>.
?Personvar14 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar15.
?Personvar15 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar15 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?PersonResidentialFacilityLocalAdministrativeRegionCountyDesignativeName.
?Personvar2 <http://purl.obolibrary.org/obo/RO_0001025> ?Personvar17.
?Personvar17 a <http://www.ontologyrepository.com/CommonCoreOntologies/PostalZone>.
?Personvar17 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar18.
?Personvar18 a <http://www.ontologyrepository.com/CommonCoreOntologies/PostalCode>.
?Personvar18 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar19.
?Personvar19 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar19 <http://www.ontologyrepository.com/CommonCoreOntologies/has_integer_value> ?PersonResidentialFacilityPostalZonePostalCode.
?Personvar2 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar21.
?Personvar21 a <http://www.ontologyrepository.com/CommonCoreOntologies/StreetAddress>.
?Personvar21 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar22.
?Personvar22 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar22 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?PersonResidentialFacilityStreetAddress.
?Personvar0 <http://www.ontologyrepository.com/CommonCoreOntologies/designated_by> ?Personvar24.
?Personvar24 a <http://www.ontologyrepository.com/CommonCoreOntologies/ProperName>.
?Personvar24 <http://purl.obolibrary.org/obo/BFO_0000051> ?Personvar25.
?Personvar25 a <http://www.ontologyrepository.com/CommonCoreOntologies/FamilyName>.
?Personvar25 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar26.
?Personvar26 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar26 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?PersonFamilyName.
?Personvar24 <http://purl.obolibrary.org/obo/BFO_0000051> ?Personvar28.
?Personvar28 a <http://www.ontologyrepository.com/CommonCoreOntologies/GivenName>.
?Personvar28 <http://purl.obolibrary.org/obo/RO_0010001> ?Personvar29.
?Personvar29 a <http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity>.
?Personvar29 <http://www.ontologyrepository.com/CommonCoreOntologies/has_text_value> ?PersonGivenName.
}